[toolchain]
anchor_version = "1.0.2"

[features]
seeds = true
skip-lint = false

[programs.localnet]
escrow = "AuSvDxVH1ovWbGLiSFtaAbkVEy5ophRV9Z3RHmd3smgd"

[programs.devnet]
escrow = "AuSvDxVH1ovWbGLiSFtaAbkVEy5ophRV9Z3RHmd3smgd"

[registry]
url = "https://api.anchor-lang.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/escrow",
]
